# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dﾅ行Lambﾅ行.  Music, Art, Lifestyle
title-bold: Dﾅ行Lambﾅ行
title-normal: Music, Art, Lifestyle
email: team@doslambos.com
description: We play music in Chicago
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.doslambos.com" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Chicago
state: IL
zip_code: 60606
country: United States of America
phone: (716) 555-5555

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 60

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/diwant
googleplus_url: https://plus.google.com/u/0/+DosLambos
instagram_url: https://instagram.com/doslambos
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/doslambos

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: doslambos
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
